name: CI

on:
  push:
    branches:
      - upadhyay-test
  

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.0
      
      - name: Verify Changed files
        uses: tj-actions/changed-files@v8.5
        id: verify-changed-files
        with:
          files: |
            sample.txt
            
      
      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done
